security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    crus:  { password: crpass, roles: [ 'ROLE_USER', 'ROLE_ADMIN' ] }
                    irus:  { password: conopida, roles: [ 'ROLE_USER', 'ROLE_ADMIN' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/admin/
            form_login:
                check_path: login_check
                login_path: /login
            logout:
                path:   /admin/logout
                target: /admin/
                invalidate_session: false #remove this on production server, local dev fix only!
            #anonymous: ~
            http_basic:
                realm: "Secured Admin Area"

    access_control:

        - { path: ^/admin/system/, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/status/, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    acl:
        connection: default
